/* Do not modify this file.  */
/* It is created automatically by the Makefile.  */
#include "defs.h"      /* For initialize_file_ftype.  */
#include "call-cmds.h" /* For initialize_all_files.  */
extern initialize_file_ftype _initialize_gdbtypes;
extern initialize_file_ftype _initialize_annotate;
extern initialize_file_ftype _initialize_auxv;
extern initialize_file_ftype _initialize_breakpoint;
extern initialize_file_ftype _initialize_regcache;
extern initialize_file_ftype _initialize_charset;
extern initialize_file_ftype _initialize_dummy_frame;
extern initialize_file_ftype _initialize_source;
extern initialize_file_ftype _initialize_values;
extern initialize_file_ftype _initialize_valops;
extern initialize_file_ftype _initialize_valarith;
extern initialize_file_ftype _initialize_valprint;
extern initialize_file_ftype _initialize_printcmd;
extern initialize_file_ftype _initialize_symtab;
extern initialize_file_ftype _initialize_symfile;
extern initialize_file_ftype _initialize_symmisc;
extern initialize_file_ftype _initialize_infcall;
extern initialize_file_ftype _initialize_infcmd;
extern initialize_file_ftype _initialize_infrun;
extern initialize_file_ftype _initialize_stack;
extern initialize_file_ftype _initialize_thread;
extern initialize_file_ftype _initialize_interpreter;
extern initialize_file_ftype _initialize_macrocmd;
extern initialize_file_ftype _initialize_event_loop;
extern initialize_file_ftype _initialize_gdbarch;
extern initialize_file_ftype _initialize_gdbarch_utils;
extern initialize_file_ftype _initialize_gdb_osabi;
extern initialize_file_ftype _initialize_copying;
extern initialize_file_ftype _initialize_mem;
extern initialize_file_ftype _initialize_parse;
extern initialize_file_ftype _initialize_language;
extern initialize_file_ftype _initialize_frame_reg;
extern initialize_file_ftype _initialize_signals;
extern initialize_file_ftype _initialize_kod;
extern initialize_file_ftype _initialize_gdb_events;
extern initialize_file_ftype _initialize_exec;
extern initialize_file_ftype _initialize_objfiles;
extern initialize_file_ftype _initialize_observer;
extern initialize_file_ftype _initialize_maint_cmds;
extern initialize_file_ftype _initialize_demangler;
extern initialize_file_ftype _initialize_dbxread;
extern initialize_file_ftype _initialize_coffread;
extern initialize_file_ftype _initialize_elfread;
extern initialize_file_ftype _initialize_dwarf2_read;
extern initialize_file_ftype _initialize_mipsread;
extern initialize_file_ftype _initialize_stabsread;
extern initialize_file_ftype _initialize_core;
extern initialize_file_ftype _initialize_dwarf2_frame;
extern initialize_file_ftype _initialize_ada_language;
extern initialize_file_ftype _initialize_c_language;
extern initialize_file_ftype _initialize_f_language;
extern initialize_file_ftype _initialize_objc_language;
extern initialize_file_ftype _initialize_objc_lang;
extern initialize_file_ftype _initialize_ui_out;
extern initialize_file_ftype _initialize_cli_out;
extern initialize_file_ftype _initialize_varobj;
extern initialize_file_ftype _initialize_java_language;
extern initialize_file_ftype _initialize_m2_language;
extern initialize_file_ftype _initialize_pascal_language;
extern initialize_file_ftype _initialize_pascal_valprint;
extern initialize_file_ftype _initialize_scheme_language;
extern initialize_file_ftype _initialize_complaints;
extern initialize_file_ftype _initialize_typeprint;
extern initialize_file_ftype _initialize_cp_valprint;
extern initialize_file_ftype _initialize_f_valprint;
extern initialize_file_ftype _initialize_nlmread;
extern initialize_file_ftype _initialize_serial;
extern initialize_file_ftype _initialize_mdebugread;
extern initialize_file_ftype _initialize_user_regs;
extern initialize_file_ftype _initialize_frame;
extern initialize_file_ftype _initialize_frame_unwind;
extern initialize_file_ftype _initialize_doublest;
extern initialize_file_ftype _initialize_frame_base;
extern initialize_file_ftype _initialize_gnu_v2_abi;
extern initialize_file_ftype _initialize_gnu_v3_abi;
extern initialize_file_ftype _initialize_hpacc_abi;
extern initialize_file_ftype _initialize_cp_abi;
extern initialize_file_ftype _initialize_cp_support;
extern initialize_file_ftype _initialize_cp_namespace;
extern initialize_file_ftype _initialize_reggroup;
extern initialize_file_ftype _initialize_fix;
extern initialize_file_ftype _initialize_checkpoint;
extern initialize_file_ftype _initialize_solib;
extern initialize_file_ftype _initialize_null_solib;
extern initialize_file_ftype _initialize_x86_shared_tdep;
extern initialize_file_ftype _initialize_ada_exp;
extern initialize_file_ftype _initialize_core_macho;
extern initialize_file_ftype _initialize_i386_tdep;
extern initialize_file_ftype _initialize_i386_macosx_tdep;
extern initialize_file_ftype _initialize_remote_kdp;
extern initialize_file_ftype _initialize_remote_mobile;
extern initialize_file_ftype _initialize_macosx_tdep;
extern initialize_file_ftype _initialize_machoread;
extern initialize_file_ftype _initialize_load_plugin;
extern initialize_file_ftype _initialize_macosx_nat_dyld;
extern initialize_file_ftype _initialize_macosx_nat_dyld_process;
extern initialize_file_ftype _initialize_symread;
extern initialize_file_ftype _initialize_pefread;
extern initialize_file_ftype _initialize_ser_hardwire;
extern initialize_file_ftype _initialize_ser_tcp;
extern initialize_file_ftype _initialize_fork_child;
extern initialize_file_ftype _initialize_inftarg;
extern initialize_file_ftype _initialize_i386_nat;
extern initialize_file_ftype _initialize_macosx_nat_watchpoint;
extern initialize_file_ftype _initialize_macosx_nat_dyld;
extern initialize_file_ftype _initialize_macosx_nat_dyld_process;
extern initialize_file_ftype _initialize_macosx_inferior;
extern initialize_file_ftype _initialize_macosx_inferior_debug;
extern initialize_file_ftype _initialize_macosx_nat_sigthread;
extern initialize_file_ftype _initialize_macosx_nat_excthread;
extern initialize_file_ftype _initialize_macosx_mutils;
extern initialize_file_ftype _initialize_threads;
extern initialize_file_ftype _initialize_macosx_info_commands;
extern initialize_file_ftype _initialize_macosx_nat;
extern initialize_file_ftype _initialize_remote_darwin_kernel;
extern initialize_file_ftype _initialize_load_plugin;
extern initialize_file_ftype _initialize_remote;
extern initialize_file_ftype _initialize_dcache;
extern initialize_file_ftype _initialize_sr_support;
extern initialize_file_ftype _initialize_tracepoint;
extern initialize_file_ftype _initialize_ax_gdb;
extern initialize_file_ftype _initialize_cli_dump;
extern initialize_file_ftype _initialize_cli_logging;
extern initialize_file_ftype _initialize_cli_interp;
extern initialize_file_ftype _initialize_mi_out;
extern initialize_file_ftype _initialize_mi_cmds;
extern initialize_file_ftype _initialize_mi_cmd_env;
extern initialize_file_ftype _initialize_mi_cmd_var;
extern initialize_file_ftype _initialize_mi_interp;
extern initialize_file_ftype _initialize_mi_main;
extern initialize_file_ftype _initialize_gdb_mi_common;
extern initialize_file_ftype _initialize_inflow;
void
initialize_all_files (void)
{
  _initialize_gdbtypes ();
  _initialize_annotate ();
  _initialize_auxv ();
  _initialize_breakpoint ();
  _initialize_regcache ();
  _initialize_charset ();
  _initialize_dummy_frame ();
  _initialize_source ();
  _initialize_values ();
  _initialize_valops ();
  _initialize_valarith ();
  _initialize_valprint ();
  _initialize_printcmd ();
  _initialize_symtab ();
  _initialize_symfile ();
  _initialize_symmisc ();
  _initialize_infcall ();
  _initialize_infcmd ();
  _initialize_infrun ();
  _initialize_stack ();
  _initialize_thread ();
  _initialize_interpreter ();
  _initialize_macrocmd ();
  _initialize_event_loop ();
  _initialize_gdbarch ();
  _initialize_gdbarch_utils ();
  _initialize_gdb_osabi ();
  _initialize_copying ();
  _initialize_mem ();
  _initialize_parse ();
  _initialize_language ();
  _initialize_frame_reg ();
  _initialize_signals ();
  _initialize_kod ();
  _initialize_gdb_events ();
  _initialize_exec ();
  _initialize_objfiles ();
  _initialize_observer ();
  _initialize_maint_cmds ();
  _initialize_demangler ();
  _initialize_dbxread ();
  _initialize_coffread ();
  _initialize_elfread ();
  _initialize_dwarf2_read ();
  _initialize_mipsread ();
  _initialize_stabsread ();
  _initialize_core ();
  _initialize_dwarf2_frame ();
  _initialize_ada_language ();
  _initialize_c_language ();
  _initialize_f_language ();
  _initialize_objc_language ();
  _initialize_objc_lang ();
  _initialize_ui_out ();
  _initialize_cli_out ();
  _initialize_varobj ();
  _initialize_java_language ();
  _initialize_m2_language ();
  _initialize_pascal_language ();
  _initialize_pascal_valprint ();
  _initialize_scheme_language ();
  _initialize_complaints ();
  _initialize_typeprint ();
  _initialize_cp_valprint ();
  _initialize_f_valprint ();
  _initialize_nlmread ();
  _initialize_serial ();
  _initialize_mdebugread ();
  _initialize_user_regs ();
  _initialize_frame ();
  _initialize_frame_unwind ();
  _initialize_doublest ();
  _initialize_frame_base ();
  _initialize_gnu_v2_abi ();
  _initialize_gnu_v3_abi ();
  _initialize_hpacc_abi ();
  _initialize_cp_abi ();
  _initialize_cp_support ();
  _initialize_cp_namespace ();
  _initialize_reggroup ();
  _initialize_fix ();
  _initialize_checkpoint ();
  _initialize_solib ();
  _initialize_null_solib ();
  _initialize_x86_shared_tdep ();
  _initialize_ada_exp ();
  _initialize_core_macho ();
  _initialize_i386_tdep ();
  _initialize_i386_macosx_tdep ();
  _initialize_remote_kdp ();
  _initialize_remote_mobile ();
  _initialize_macosx_tdep ();
  _initialize_machoread ();
  _initialize_load_plugin ();
  _initialize_macosx_nat_dyld ();
  _initialize_macosx_nat_dyld_process ();
  _initialize_symread ();
  _initialize_pefread ();
  _initialize_ser_hardwire ();
  _initialize_ser_tcp ();
  _initialize_fork_child ();
  _initialize_inftarg ();
  _initialize_i386_nat ();
  _initialize_macosx_nat_watchpoint ();
  _initialize_macosx_nat_dyld ();
  _initialize_macosx_nat_dyld_process ();
  _initialize_macosx_inferior ();
  _initialize_macosx_inferior_debug ();
  _initialize_macosx_nat_sigthread ();
  _initialize_macosx_nat_excthread ();
  _initialize_macosx_mutils ();
  _initialize_threads ();
  _initialize_macosx_info_commands ();
  _initialize_macosx_nat ();
  _initialize_remote_darwin_kernel ();
  _initialize_load_plugin ();
  _initialize_remote ();
  _initialize_dcache ();
  _initialize_sr_support ();
  _initialize_tracepoint ();
  _initialize_ax_gdb ();
  _initialize_cli_dump ();
  _initialize_cli_logging ();
  _initialize_cli_interp ();
  _initialize_mi_out ();
  _initialize_mi_cmds ();
  _initialize_mi_cmd_env ();
  _initialize_mi_cmd_var ();
  _initialize_mi_interp ();
  _initialize_mi_main ();
  _initialize_gdb_mi_common ();
  _initialize_inflow ();
}
